# Generated by Django 3.1.1 on 2020-09-03 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conducteur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nbre_place', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Passager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('prenom', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart', models.CharField(max_length=255)),
                ('arrive', models.CharField(max_length=255)),
                ('prix', models.FloatField()),
                ('conducteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.conducteur')),
                ('passager', models.ManyToManyField(to='main.Passager')),
            ],
        ),
        migrations.AddField(
            model_name='passager',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.person'),
        ),
        migrations.AddField(
            model_name='conducteur',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.person'),
        ),
    ]
